#ifndef __SYSCALL_H__
#define __SYSCALL_H__

#define MAX_SYSCALL 349
#define S(str) [SYS_##str]

int avail_syscall[MAX_SYSCALL] = {
	S(restart_syscall) = -1,
	S(exit) = 1, 
	S(read) = -1, 
	S(write) = -1,
	S(execve) = 1,
	S(time) = -1,
	S(lseek) = -1,
	S(stime) = -1,
	S(alarm) = -1,
	S(oldfstat) = -1,
	S(access) = -1,
	S(times) = -1,
	S(brk) = -1,
	S(oldolduname) = -1,
	S(ustat) = -1,
	S(getrlimit) = -1,
	S(getrusage) = -1,
	S(gettimeofday) = -1,
	S(oldstat) = -1,
	S(readlink) = -1,
	S(mmap) = -1,
	S(munmap) = -1,
	S(truncate) = -1,
	S(ftruncate) = -1,
	S(getpriority) = -1,
	S(statfs) = -1,
	S(fstatfs) = -1,
	S(stat) = -1,
	S(lstat) = -1,
	S(fstat) = -1,
	S(olduname) = -1,
	S(uname) = -1,
	S(mprotect) = -1,
	S(mlock) = -1,
	S(munlock) = -1,
	S(mlockall) = -1,
	S(munlockall) = -1,
	S(mremap) = -1,
	S(pread64) = -1,
	S(pwrite64) = -1,
	S(mmap2) = -1,
	S(truncate64) = -1,
	S(ftruncate64) = -1,
	S(stat64) = -1,
	S(lstat64) = -1,
	S(fstat64) = -1,
	S(statfs64) = -1,
	S(set_thread_area) = 2,
	S(get_thread_area) = -1,
	S(exit_group) = 1,
	S(fstatfs64) = -1,
	S(fstatat64) = -1,
	S(getcwd) = -1,
	S(open) = -1,
	S(close) = -1,
	S(dup3) = -1,
	S(pipe2) = -1,
};

#endif /* __SYSCALL_H__ */
